/// \file Counterexample-Guided Inductive Synthesis

#ifndef CPROVER_CEGIS_DANGER_META_LITERALS_H
#define CPROVER_CEGIS_DANGER_META_LITERALS_H

#define DANGER_PREFIX "__CPROVER_danger_"
#define DANGER_EXECUTE DANGER_PREFIX "execute"
#define DANGER_X0_PLACEHOLDER_PREFIX DANGER_PREFIX "x0_"

#endif // CPROVER_CEGIS_DANGER_META_LITERALS_H
